- livereload/server.py
@lepture 
We can use glob in command by setting shell to True:
```python
shell('ls *.html', output='result.txt', cwd='./pages', shell=True)
```
So we don't need to use `glob` to grab the list of `./pages/*.html`.
> Add ``shell`` parameter for shell.

- livereload/server.py
This makes it easier to debug in case of a "port already in use"
exception.
> print "Serving on.." before attempting to do so

- livereload/server.py
debug=True makes tornado reload the (livereload) app when its code
changes, which is not useful normally.  Additionally tornado does not
support using inotify, but uses `epoll` on Linux.
> Default to debug=False with no app

- README.rst
Mention Guardfiles that were used by older versions of Python LiveReload,
explain how to replace them with simple Python scripts. Provide an example for
Sphinx.
Fixes #94.
> Explain how to use it when you don't have a WSGI app

- livereload/server.py
Uses JavaScript to dynamically inject the client's hostname.
This allows for serving on 0.0.0.0, where a rendered hostname of
"0.0.0.0" would not resolve necessarily to the server's address.
> server: use JS location.hostname with livereload.js resource

- README.rst
- livereload/cli.py
Add --wait parameter, useful when working with templates that need to be regenerated before reloading
> Expose delay parameter in command line tool

- docs/conf.py
Closes #117
Fixes the GitHub ribbon link here: https://livereload.readthedocs.org/en/latest/
> Add theme option for GitHub link

- docs/Makefile
Otherwise the build fails with a cryptic theme error:
no theme named 'flask_small' found (missing theme.conf?)
> 'make docs': initialize git submodules automatically

- livereload/cli.py
- livereload/watcher.py
`--wait` is great for waiting for build processes to complete that can't be well integrated. Unfortunately, sometimes full seconds are too granular (e.g. sometimes waiting `0.2s` would be ideal). Tornado supports floating point seconds already so this is a simple integration:
http://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop.time
In this PR:
- Moved `--wait`/`delay` from `int` to `float
> Support waiting parts of seconds

- livereload/watcher.py
As pyinotify is not a dependency that gets installed, some users may already
have an older version installed which does not include Tornado support (added
in pyinotify version 0.9.4). Unfortunately, pyinotify does not make their
version available programicaly, so we check that the neccessary class is
present. Now users with older versions will fall back gracefully just like
those who do not have any version isntalled.
For reference, at mkdocs/mkdocs#1119 we've had a few users run into this. They get an ugly error and at first we thought it was because they were using an older version of Python. Turns out they just needed to upgrade pyinotify.
> Ensure current version of pyinotify is installed before using.

- livereload/server.py
- livereload/vendors/livereload.js
- Use protocol-relative URL to access livereload.js.
- Talk to WebSocket Secure (wss://) when HTTPS is in use.
> Allow server sitting behind reverse proxy with SSL.

- livereload/server.py
resulting the browser to limbo in pending state
> Fix tornado 4.5 above not closing connections on autoreload

- livereload/server.py
- livereload/watcher.py
This logs the tasks being run, and adds `func.repr_str` to the task
function, which contains the shell command for string "functions".
> Watcher.examine: log running task

- README.rst
I spent quite some time while I finally found the reason, why Bottle
templates won't auto reload. I thing this should be mentioned in the
docs.
> Update docs about bottle template caching

- livereload/handlers.py
This fixes a bug that results in `RuntimeError: Set changed size during iteration` when a waiter is removed during iteration over the waiters.
> You cannot remove an item from a set while iterating through it

- tests/test_watcher.py
Due to a missing repr_str attribute, the function `add_count` in `TestWatcher.test_watch_file` triggered an error in `Watcher.examine()`.
Closes #171
> test_watcher: fix a failing test

- livereload/handlers.py
Solves #183 by checking file mtime on every request before returning cached etag.
> cache etag and mtime, recalc etag only on mtime change

- .gitignore
- livereload/watcher.py
- tests/test_watcher.py
Fixes #197.
- Adds assertions for deleting files to existing tests
- Detects file deletion with a "before" and "after" dictionary of modification times
- Adds docstrings to relevant methods
- Ignores common `venv` directory
> Trigger reload on deleted files

- livereload/server.py
- Log an error instead of a warning, so that the message really stands out.
- Move logging out of the first `if` clause to reduce cyclomatic complexity
- Check if `open_url_delay` is not `None`, to allow for `0` or `0.0` delay values
I can also remove the `open_url` parameter completely, if you allow me to.
> Allow zero delay when opening browser

- livereload/server.py
This is a proposed solution to issue#194 livereload uses port 0 when website is on default ports.
Please consider picking this up or equivalent fix to enable livereload on default ports. This would enable livereload to work using ngrok or other reverse proxy config.
> use default ports when windows.location.protocol is an empty string

- livereload/server.py
I added the fix when `liveport` is None running on a reverse proxy
> @ #132 | Script specifies host and port which breaks reverse proxies

- livereload/watcher.py
Sadly, currently `**` glob patterns are just ignored.
I discovered this due to its usage une the recently introduced [pelican invoke task dedicated to livereload](https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/tasks.py.jinja2#L103)
This has already been suggested as a custom watcher in #156.
However, as [Python 2 end of life is scheduled in less than 6 months](https://pythonclock.org),
I think we could rely on `glob.glob` `recursive` optional argument to be supported fairly often.
Still, this PR is fully backward-compatible as it checks for a Python minimum version of 3.5
> Support ** recursive globs by default - close #156

- livereload/watcher.py
Allows to write callback functions that can limit their processing to the scope of the modified files.
It is fully backward-compatible.
Usage example with globs:
```python
server = Server()
server.watch('**/.md', lambda paths: regenerate(paths))
```
This PR currently relies on https://github.com/lepture/python-livereload/pull/203 but could easily be dissociated
> Pass the list of changed files to the _func_ callback if it supports arguments

- livereload/server.py
This fixes the use of errno to support python 2.7 as well as 3.7 and newer.
> update import and use of errno

- livereload/server.py
Upstream tornado devs are not going to configure the async event
loop due to it causing performance issues on other systems.
Instead they suggest using this workaround.
https://github.com/tornadoweb/tornado/issues/2608
> Windows 3.8 asyncio fix

- setup.py
Adjusts the `install_requires` to install the latest tornado for Python 3.x and limits the version to 5.1.1 if the Python version is 2.7
> install older version of tornado for 2.7

- livereload/server.py
- livereload/watcher.py
- setup.py
Missed a few things in a couple PRs before.
The watcher no longer worked with Python 2.7 and versions before 3.7 don't have asyncio.
> Python 2.7 support

- CHANGES.rst
- livereload/__init__.py
- setup.py
Update version and changes listing.
> new release update

- livereload/server.py
With a web page containing **tow** `<head>` sections,
the current version of `livereload` breaks with this error:
```
[E 220721 20:20:24 web:1791] Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5500', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1'
)
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1706, in _execute
result = await result
File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 2650, in get
await self.flush()
File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1095, in flush
return self.request.connection.write_headers(
File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 465, in write_headers
data += …
```
> Fix LiveScriptInjector so that <script> is never injected twice

- setup.py
The long description points to `README.rst`, which doesn't exist and makes `pip install .` fail.
This changes the filename to `README.md`. However, we may have to change it in `MANIFEST` as well.
> Fix long_description in setup.py

- livereload/handlers.py
I use the following `watch_and_serve.py` script:
```python
#!/usr/bin/env python3
from os.path import dirname
from livereload import Server
from other_module import gen_css_bundle
SERVER = Server()
SERVER.watch('index.html')
SERVER.watch('assets/css/main.css', gen_css_bundle)
SERVER.serve(root='.')
```
The `gen_css_bundle` function takes a few milliseconds to execute and **edit index.html to insert the new bundle filename**.
When I run this script and edit `main.css`, I see the following logs:
```
[I 210327 10:57:21 watcher:104] Running task: gen_css_bundle (delay: 3)
[I 210327 10:57:21 handlers:95] Reload 1 waiters: ./assets/css/main.css
[I 210327 10:57:22 handlers:82] Ignore: ./index.html
```
I want to introduce a mechanism in `livereload` in order to control this "ignore" logic,
so …
> Making reload_time in LiveReloadHandler.poll_tasks configurable

- livereload/server.py
stdout was already correctly decoded, but not stderr.
> Fix encoding of error messages

- livereload/handlers.py
Fixes runtime error:
NameError: name 'DEFAULT_RELOAD_TIME' is not defined
> Use correct scope for DEFAULT_RELOAD_TIME

- livereload/server.py
I'm using Flask v3 and Python 3.11.  When starting up my server I got the following error ([and it seems I'm not the only one):
](https://stackoverflow.com/questions/77333325/setting-up-auto-refresh-with-flask-on-template-change)
```
Traceback (most recent call last):
File "/Users/john/venv/ema-cSETeqck/lib/python3.11/site-packages/tornado/web.py", line 1767, in _execute
result = self.prepare()
^^^^^^^^^^^^^^
File "/Users/john/venv/ema-cSETeqck/lib/python3.11/site-packages/tornado/web.py", line 3149, in prepare
self.fallback(self.request)
File "/Users/john/venv/ema-cSETeqck/lib/python3.11/site-packages/livereload/server.py", line 135, in __call__
app_response = self.wsgi_app(WSGIContainer.environ(request), start_response)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WSGIContainer.environ() …
```
> Fix issue with WSGI container error

- livereload/server.py
Hello! 
Thank you for this amazing library 🤩 !
It works really well when watching static assets and templates, however I noticed that changes to `.py` files fails due to a runtime error. This issue has been previously recorded in #170, and marked as "needs more info". In my Flask project, I'm able to reproduce it continuously on every change to a .py file in the project.
After following the comments on the ticket, I realized the technique to restart tornado can be improved in order to avoid the runtime error. This PR introduces a slight change in the order of disposing of resources:
From the [docs](https://github.com/tornadoweb/tornado/blob/9c06f98025c1bca98114d197361f27f5530067f6/tornado/ioloop.py#L379)
* The call to `IOLoop.instance().start()` does not return until the program calls …
> fix(#170): wait for the IOLoop to stop before attempting to close it
